### ISSUE TITLE
Cannot read property 'val' of null

### ISSUE THREAD

**Issue by Zwer2k** [Baumert7269/ioBroker.repetierserver#27]
Get error message when connecting 

-- | -- | -- | --
-- | -- | -- | --
repetierserver.0 | 2021-12-19 16:11:00.897 | error | Cannot read property 'val' of null
repetierserver.0 | 2021-12-19 16:11:00.897 | error | TypeError: Cannot read property 'val' of null at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.repetierserver/main.js:1003:63) at processImmediate (internal/timers.js:463:21)
repetierserver.0 | 2021-12-19 16:11:00.896 | error | uncaught exception: Cannot read property 'val' of null
repetierserver.0 | 2021-12-19 16:11:00.389 | warn | Object of state "repetierserver.0.IP_192_168_44_4.Printer_ANET_A8.PrintModel.Modelle" is missing the required property "common.type"

**Comment by Zwer2k** [comment]
Seems to be fixed in v0.0.8. Why is the version not offered in ioBroker:latest?
