### ISSUE TITLE
Cannot read property 'length' of undefined / Neustartschleife

### ISSUE THREAD

**Issue by verdampfer** [Baumert7269/ioBroker.repetierserver#30]
IO brooker schaltet die Insatz ab da sie sich in einem restartloop befindet

<html><body>

repetierserver.0 | 2022-01-14 19:20:03.002 | warn | Read-only state "repetierserver.0.info.connection" has been written without ack-flag with value "false"
-- | -- | -- | --
repetierserver.0 | 2022-01-14 19:20:02.945 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
repetierserver.0 | 2022-01-14 19:20:02.943 | info | terminating
repetierserver.0 | 2022-01-14 19:20:02.942 | info | Repetier-Server-Dienst gestoppt ...
repetierserver.0 | 2022-01-14 19:20:02.942 | info | Repetier-Server-Verbindung beendet ...
repetierserver.0 | 2022-01-14 19:20:02.941 | info | Repetier-Server-Service bereinigt ...
repetierserver.0 | 2022-01-14 19:20:02.935 | error | Cannot read property 'length' of undefined
repetierserver.0 | 2022-01-14 19:20:02.935 | error | TypeError: Cannot read property 'length' of undefined     at refreshState (/opt/iobroker/node_modules/iobroker.repetierserver/main.js:948:74)     at processTicksAndRejections (internal/process/task_queues.js:97:5)
repetierserver.0 | 2022-01-14 19:20:02.934 | error | unhandled promise rejection: Cannot read property 'length' of undefined
repetierserver.0 | 2022-01-14 19:20:02.933 | error | Unhandled  promise rejection. This error originated either by throwing inside of  an async function without a catch block, or by rejecting a promise which  was not handled with .catch().

</body>
</html>

**Comment by verdampfer** [comment]
![2222](https://user-images.githubusercontent.com/97757025/149566314-fb671d3a-0582-491a-9794-addf0c0136c8.JPG)
![11111](https://user-images.githubusercontent.com/97757025/149566320-25bf098e-7346-45f1-b818-9187da6cad60.JPG)
